/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BudgetTracker;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.*;
import java.io.*;
/**
 *
 * @author Marquis
 */
public class AdminJFrame extends javax.swing.JFrame {
    private final String currentUsername;
    private final String currentRole;
    private final String USERS_PATH = "C:/BudgetTracker/users.txt";
    private final String TRANSACTIONS_PATH = "C:/BudgetTracker/transactions.txt";
    /**
     * Creates new form AdminJFrame
     */

    public AdminJFrame(String username, String role) {
        initComponents();
        this.currentUsername = username; 
        this.currentRole = role;
        initializeUI();
        loadUsersWithSummaries();
        applyTheme();
    }
    
    private void applyTheme() {
        // Apply gradient background
        Theme.applyGradientBackground(getContentPane());

        // Apply dark theme to all components
        for (Component comp : getContentPane().getComponents()) {
            if (comp instanceof JComponent) {
                Theme.applyDarkTheme((JComponent) comp);
            }
        }
    }

    private void initializeUI() {
        txtUserSummaries.setFont(new java.awt.Font("Monospaced", 0, 12));
        txtUserSummaries.setEditable(false);
    }
    
    private void loadUsersWithSummaries() {
        File usersFile = new File(USERS_PATH);
        txtUserSummaries.setText("");

        try (BufferedReader br = new BufferedReader(new FileReader(usersFile))) {
            // Create header
            txtUserSummaries.append(String.format("%-15s %-10s %-12s %-12s %-12s\n", 
                "Username", "Role", "Income", "Expense", "Balance"));
            txtUserSummaries.append("--------------------------------------------------------------------------------\n");
            
            String line;
            while ((line = br.readLine()) != null) {
                String[] parts = line.split(",");
                if (parts.length == 3) {
                    String user = parts[0];
                    String role = parts[2];
                    double[] totals = calculateUserTotals(user);
                    
                    txtUserSummaries.append(String.format("%-15s %-10s $%-11.2f $%-11.2f $%-11.2f\n", 
                        user,
                        role,
                        totals[0],
                        totals[1],
                        totals[0] - totals[1]
                    ));
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error loading users: " + e.getMessage());
        }
    }

    private double[] calculateUserTotals(String username) {
        double[] totals = new double[2]; // [0] = income, [1] = expense
        File transactionsFile = new File(TRANSACTIONS_PATH);

        try (BufferedReader br = new BufferedReader(new FileReader(transactionsFile))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] parts = line.split("\\|");
                if (parts.length == 5 && parts[0].equals(username)) {
                    double amount = Double.parseDouble(parts[2]);
                    if (parts[1].equalsIgnoreCase("income")) {
                        totals[0] += amount;
                    } else {
                        totals[1] += amount;
                    }
                }
            }
        } catch (IOException | NumberFormatException e) {
            // Silent error - return current totals
        }
        return totals;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        txtUserSummaries = new javax.swing.JTextArea();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Budget Nata - Admin");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Agency FB", 0, 27)); // NOI18N
        jLabel1.setText("User Management");

        btnBack.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        btnBack.setText("Back to Main");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Righteous", 0, 14)); // NOI18N
        jLabel2.setText("User List:");

        txtUserSummaries.setEditable(false);
        txtUserSummaries.setColumns(20);
        txtUserSummaries.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txtUserSummaries.setRows(5);
        scrollPane.setViewportView(txtUserSummaries);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(scrollPane, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 244, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        MainJFrame main = new MainJFrame(currentUsername, currentRole);
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed
   
    private void loadUsers() {
        File usersFile = new File(USERS_PATH);
        txtUserSummaries.setText("");

        try (BufferedReader br = new BufferedReader(new FileReader(usersFile))) {
            txtUserSummaries.append(String.format("%-15s %-10s\n", "Username", "Role"));
            txtUserSummaries.append("---------------------------\n");
            
            String line;
            while ((line = br.readLine()) != null) {
                String[] parts = line.split(",");
                if (parts.length == 3 && !parts[0].equals("admin")) {
                    txtUserSummaries.append(String.format("%-15s %-10s\n", 
                        parts[0], // Username
                        parts[2]  // Role
                    ));
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error loading users: " + e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            new AdminJFrame("admin", "admin").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTextArea txtUserSummaries;
    // End of variables declaration//GEN-END:variables
}
