/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BudgetTracker;
import javax.swing.*;
import java.awt.event.*;
import java.awt.*;
import java.io.*;
/**
 *
 * @author Marquis
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private final String username;
    private final String role;
    private final String TRANSACTIONS_PATH = "C:/BudgetTracker/transactions.txt";
    private boolean isAdmin;

    public MainJFrame(String username, String role) {
        initComponents();
        this.username = username;
        this.role = role;
        this.isAdmin = "admin".equals(role);
        initializeUI();
        loadTransactions();
        applyTheme();
    }
    
    private void applyTheme() {
        // Apply gradient background
        Theme.applyGradientBackground(getContentPane());

        // Apply dark theme to all components
        for (Component comp : getContentPane().getComponents()) {
            if (comp instanceof JComponent) {
                Theme.applyDarkTheme((JComponent) comp);
            }
        }
    }

    private void initializeUI() {
        lblWelcome.setText("Welcome, " + username + " (" + role + ")");
        txtTransactions.setFont(new java.awt.Font("Monospaced", 0, 12));
        txtTransactions.setEditable(false);
        btnManageUsers.setVisible(isAdmin);
    }

    private void setupWindowListener() {
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowActivated(WindowEvent e) {
                loadTransactions(); // Refresh when window gains focus
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lblTitle = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        lblTransactionEntryPanel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmbType = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        txtAmount = new javax.swing.JTextField();
        txtDescription = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnSummary = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        lblTransactionEntryPanel1 = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        txtTransactions = new javax.swing.JTextArea();
        btnManageUsers = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        lblTitle.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        lblTitle.setText("Nata!");

        lblTitle1.setFont(new java.awt.Font("Lucida Calligraphy", 0, 24)); // NOI18N
        lblTitle1.setText("Budget");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Budget Nata!");
        setResizable(false);

        lblWelcome.setFont(new java.awt.Font("Agency FB", 0, 29)); // NOI18N
        lblWelcome.setText("Welcome!");

        lblTransactionEntryPanel.setFont(new java.awt.Font("Righteous", 0, 14)); // NOI18N
        lblTransactionEntryPanel.setText("Transaction Entry Panel:");

        jLabel1.setFont(new java.awt.Font("Righteous", 0, 12)); // NOI18N
        jLabel1.setText("Type:");

        cmbType.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        cmbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Expense", "Income" }));
        cmbType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTypeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Righteous", 0, 12)); // NOI18N
        jLabel2.setText("Date:");

        jLabel3.setFont(new java.awt.Font("Righteous", 0, 12)); // NOI18N
        jLabel3.setText("Amount:");

        jLabel4.setFont(new java.awt.Font("Righteous", 0, 12)); // NOI18N
        jLabel4.setText("Description:");

        txtDescription.setAutoscrolls(false);

        btnAdd.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        btnAdd.setText("Add Transaction");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnSummary.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        btnSummary.setText("Show Summary");
        btnSummary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSummaryActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        lblTransactionEntryPanel1.setFont(new java.awt.Font("Righteous", 0, 14)); // NOI18N
        lblTransactionEntryPanel1.setText("Transaction History:");

        txtTransactions.setBackground(new java.awt.Color(255, 255, 255));
        txtTransactions.setColumns(20);
        txtTransactions.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txtTransactions.setForeground(new java.awt.Color(51, 51, 51));
        txtTransactions.setRows(5);
        scrollPane.setViewportView(txtTransactions);

        btnManageUsers.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnManageUsers.setText("Manage Users");
        btnManageUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageUsersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnSummary, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(113, 113, 113)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                        .addComponent(txtAmount))
                                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(btnManageUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTransactionEntryPanel)
                            .addComponent(lblTransactionEntryPanel1)
                            .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLogout)
                    .addComponent(lblWelcome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTransactionEntryPanel)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAdd)
                        .addComponent(btnSummary))
                    .addComponent(btnManageUsers))
                .addGap(12, 12, 12)
                .addComponent(lblTransactionEntryPanel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String type = cmbType.getSelectedItem().toString();
        String amountStr = txtAmount.getText().trim();
        String date = txtDate.getText().trim();
        String description = txtDescription.getText().trim();

        // Validate empty fields
        if (amountStr.isEmpty() || date.isEmpty() || description.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields are required");
            return;
        }

        // Validate amount format
        try {
            double amount = Double.parseDouble(amountStr);
            if (amount <= 0) {
                JOptionPane.showMessageDialog(this, "Amount must be positive");
                return;
            }

            // Create transaction record
            String transaction = String.join("|",
                username,
                type,
                String.format("%.2f", amount),
                date,
                description
            );

            // Append to file
            try (FileWriter fw = new FileWriter(TRANSACTIONS_PATH, true)) {
                // Add newline if file not empty
                if (new File(TRANSACTIONS_PATH).length() > 0) {
                    fw.append("\n");
                }
                fw.append(transaction);

                // Update UI
                JOptionPane.showMessageDialog(this, "Transaction added successfully!");
                clearFields();
                loadTransactions(); // Refresh transaction list
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error saving transaction: " + e.getMessage());
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid amount format\nUse numbers only (e.g. 150.50)");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSummaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSummaryActionPerformed
        // TODO add your handling code here:
        double totalIncome = 0;
        double totalExpense = 0;

        try (BufferedReader br = new BufferedReader(new FileReader(TRANSACTIONS_PATH))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] parts = line.split("\\|");
                if (parts.length == 5 && ("admin".equals(role) || parts[0].equals(username))) {
                    double amount = Double.parseDouble(parts[2]);
                    if (parts[1].equalsIgnoreCase("income")) {
                        totalIncome += amount;
                    } else {
                        totalExpense += amount;
                    }
                }
            }
            
            String summary = String.format("Total Income: $%.2f\nTotal Expense: $%.2f\nBalance: $%.2f",
                                          totalIncome, totalExpense, (totalIncome - totalExpense));
            JOptionPane.showMessageDialog(this, summary);
        } catch (IOException | NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error calculating summary: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSummaryActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        LoginJFrame login = new LoginJFrame();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnManageUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageUsersActionPerformed
        // TODO add your handling code here:
        if (isAdmin) { // Double-check authorization
            AdminJFrame adminFrame = new AdminJFrame(username, role);
            adminFrame.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Unauthorized access!");
        }
    }//GEN-LAST:event_btnManageUsersActionPerformed

    private void cmbTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTypeActionPerformed
    
    private void loadTransactions() {
        File transactionsFile = new File(TRANSACTIONS_PATH);
        txtTransactions.setText(""); // Clear previous content

        // Create header
        String header = String.format("%-10s %-10s %-12s %s\n", 
                      "Type", "Amount", "Date", "Description");
        txtTransactions.append(header);
        txtTransactions.append("------------------------------------------------------------\n");

        try (BufferedReader br = new BufferedReader(new FileReader(transactionsFile))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] parts = line.split("\\|");
                if (parts.length == 5 && parts[0].equals(username)) {
                    // Format transaction line
                    String formattedLine = String.format("%-10s $%-9s %-12s %s\n",
                        parts[1], // Type
                        parts[2], // Amount
                        parts[3], // Date
                        parts[4]  // Description
                    );
                    txtTransactions.append(formattedLine);
                }
            }
        } catch (FileNotFoundException e) {
            txtTransactions.append("No transactions found\n");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error loading transactions: " + e.getMessage());
        }
    }

    private void clearFields() {
        txtAmount.setText("");
        txtDate.setText("");
        txtDescription.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame("testuser", "user").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageUsers;
    private javax.swing.JButton btnSummary;
    private javax.swing.JComboBox<String> cmbType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTransactionEntryPanel;
    private javax.swing.JLabel lblTransactionEntryPanel1;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextArea txtTransactions;
    // End of variables declaration//GEN-END:variables
}
